baseURL = "https://anniequus.com/"
languageCode = "en-au"
title = "Equus 🐴 (Annie)"

[params]
  description = "Annie Nie's personal website \"full of\" personal projects and CTF writeups, where I try not to break things"
  mediaPath = "media"
  url = "anniequus.com"

[menu]
  [[menu.main]]
    name = "About"
    weight = 1
    url = "about/"

    [[menu.main]]
      name = "Posts"
      weight = 1
      url = "posts/"

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"

[outputs]
  home = ["HTML", "RSS", "JSON"]
